-- Active: 1698814725013@@127.0.0.1@3306@pos
CREATE TABLE `Products` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) UNSIGNED NOT NULL,
    `description` VARCHAR(255) UNSIGNED NOT NULL,
    `price` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
) 